# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189npOOyiZubmawqlmgUn73tBERHTvgbd
"""

import matplotlib.pyplot as plt

training_data = [
    ["High", "Loamy", "Medium", "Warm", "Organic", "Yes"],
    ["High", "Loamy", "Medium", "Warm", "Organic", "Yes"],
    ["High", "Clay", "High", "Warm", "Organic", "No"],
    ["Medium", "Loamy", "Medium", "Warm", "Organic", "Yes"],
    ["Low", "Loamy", "High", "Cool", "Chemical", "No"],
    ["High", "Loamy", "Medium", "Warm", "Chemical", "Yes"],
    ["Medium", "Clay", "Low", "Cool", "Organic", "No"],
    ["High", "Loamy", "Medium", "Warm", "Organic", "Yes"]
]

attributes = [
    "Sunlight",
    "Soil",
    "Water",
    "Temperature",
    "Fertilizer"
]

def find_s(data):
    hypothesis = None

    for row in data:
        target = row[-1]
        example = row[:-1]

        if target == "Yes":

            if hypothesis is None:
                hypothesis = example.copy()
                print("Initial hypothesis:", hypothesis)

            else:
                for i in range(len(hypothesis)):
                    if hypothesis[i] != example[i]:
                        hypothesis[i] = "?"

                print("Updated hypothesis:", hypothesis)

    return hypothesis

final_hypothesis = find_s(training_data)

print("\nFINAL MOST SPECIFIC HYPOTHESIS")
print("======================================")

for attribute, value in zip(attributes, final_hypothesis):
    print(f"{attribute:15} : {value}")

specificity = [
    1 if value != "?" else 0
    for value in final_hypothesis
]

plt.figure(figsize=(9, 5))

bars = plt.bar(attributes, specificity)

plt.title("FIND-S Final Hypothesis Specificity")
plt.xlabel("Attributes")
plt.ylabel("Specific Attribute (1) / Generalized (0)")
plt.ylim(0, 1.2)

for bar, value in zip(bars, final_hypothesis):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.03,
        value,
        ha="center",
        fontsize=11
    )

plt.xticks(rotation=20)
plt.grid(axis="y", linestyle="--", alpha=0.4)
plt.show()